export interface VerifiedFood {
  id: string;
  name: string;
  category: 'Proteins' | 'Carbohydrates' | 'Fruits & Vegetables' | 'Dairy & Alternatives' | 'Fats & Nuts' | 'Legumes & Plant';
  // All nutrients strictly per 100 grams (USDA FoodData Central standard)
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number; // in mg
  portionTip?: string;
  // Comprehensive USDA Micronutrients per 100g
  micros?: Record<string, number | undefined>;
}

export const VERIFIED_FOOD_CATALOG: VerifiedFood[] = [
  // ==========================================
  // --- PROTEINS ---
  // ==========================================
  {
    id: 'chicken-breast-cooked',
    name: 'Chicken breast (skinless, roasted)',
    category: 'Proteins',
    kcal: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 74,
    portionTip: '1 medium breast ≈ 170g',
    micros: {
      'Vitamin B1': 0.07,
      'Vitamin B2': 0.12,
      'Vitamin B3': 13.7,
      'Vitamin B5': 1.5,
      'Vitamin B6': 0.60,
      'Vitamin B7': 1.6,
      'Folate': 4,
      'Vitamin B12': 0.34,
      'Choline': 85.0,
      'Magnesium': 29,
      'Potassium': 256,
      'Phosphorus': 228,
      'Calcium': 15,
      'Iron': 1.0,
      'Zinc': 1.0,
      'Copper': 0.05,
      'Manganese': 0.02,
      'Selenium': 27.6,
      'Iodine': 7,
    },
  },
  {
    id: 'chicken-thigh-cooked',
    name: 'Chicken thigh (skinless, roasted)',
    category: 'Proteins',
    kcal: 209,
    protein: 26.0,
    carbs: 0.0,
    fat: 10.9,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 86,
    portionTip: '1 medium thigh ≈ 115g',
    micros: {
      'Vitamin A': 12,
      'Vitamin B1': 0.08,
      'Vitamin B2': 0.24,
      'Vitamin B3': 6.5,
      'Vitamin B5': 1.2,
      'Vitamin B6': 0.35,
      'Vitamin B7': 2.1,
      'Folate': 8,
      'Vitamin B12': 0.45,
      'Choline': 76.0,
      'Magnesium': 24,
      'Potassium': 239,
      'Phosphorus': 198,
      'Calcium': 11,
      'Iron': 1.3,
      'Zinc': 2.1,
      'Copper': 0.07,
      'Manganese': 0.02,
      'Selenium': 24.3,
      'Iodine': 6,
    },
  },
  {
    id: 'turkey-breast-cooked',
    name: 'Turkey breast (skinless, roasted)',
    category: 'Proteins',
    kcal: 147,
    protein: 30.1,
    carbs: 0.0,
    fat: 2.1,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 68,
    portionTip: '1 thick slice ≈ 85g',
    micros: {
      'Vitamin B1': 0.06,
      'Vitamin B2': 0.15,
      'Vitamin B3': 10.4,
      'Vitamin B5': 1.1,
      'Vitamin B6': 0.81,
      'Vitamin B7': 1.8,
      'Folate': 7,
      'Vitamin B12': 0.37,
      'Choline': 84.0,
      'Magnesium': 30,
      'Potassium': 293,
      'Phosphorus': 230,
      'Calcium': 14,
      'Iron': 1.4,
      'Zinc': 1.8,
      'Copper': 0.06,
      'Selenium': 29.8,
      'Iodine': 8,
    },
  },
  {
    id: 'beef-ground-90-10',
    name: 'Lean ground beef 90/10 (pan-broiled)',
    category: 'Proteins',
    kcal: 217,
    protein: 26.1,
    carbs: 0.0,
    fat: 11.8,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 75,
    portionTip: '1 standard patty ≈ 115g',
    micros: {
      'Vitamin B1': 0.05,
      'Vitamin B2': 0.18,
      'Vitamin B3': 5.4,
      'Vitamin B5': 0.65,
      'Vitamin B6': 0.38,
      'Vitamin B7': 3.2,
      'Folate': 9,
      'Vitamin B12': 2.6,
      'Choline': 82.0,
      'Magnesium': 21,
      'Potassium': 342,
      'Phosphorus': 215,
      'Calcium': 18,
      'Iron': 2.7,
      'Zinc': 5.7,
      'Copper': 0.08,
      'Selenium': 22.1,
      'Iodine': 11,
    },
  },
  {
    id: 'beef-ground-95-5',
    name: 'Extra lean ground beef 95/5 (cooked)',
    category: 'Proteins',
    kcal: 171,
    protein: 26.0,
    carbs: 0.0,
    fat: 6.5,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 72,
    portionTip: '1 serving ≈ 100g',
    micros: {
      'Vitamin B1': 0.05,
      'Vitamin B2': 0.19,
      'Vitamin B3': 5.7,
      'Vitamin B5': 0.68,
      'Vitamin B6': 0.40,
      'Vitamin B7': 3.4,
      'Folate': 10,
      'Vitamin B12': 2.7,
      'Choline': 86.0,
      'Magnesium': 23,
      'Potassium': 360,
      'Phosphorus': 228,
      'Calcium': 19,
      'Iron': 2.8,
      'Zinc': 6.0,
      'Copper': 0.09,
      'Selenium': 24.5,
      'Iodine': 12,
    },
  },
  {
    id: 'sirloin-steak-cooked',
    name: 'Top sirloin steak (trimmed lean, broiled)',
    category: 'Proteins',
    kcal: 207,
    protein: 30.3,
    carbs: 0.0,
    fat: 8.7,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 56,
    portionTip: '1 palm-size steak ≈ 170g',
    micros: {
      'Vitamin B1': 0.08,
      'Vitamin B2': 0.28,
      'Vitamin B3': 7.2,
      'Vitamin B5': 0.72,
      'Vitamin B6': 0.55,
      'Vitamin B7': 3.8,
      'Folate': 12,
      'Vitamin B12': 2.1,
      'Choline': 95.0,
      'Magnesium': 24,
      'Potassium': 380,
      'Phosphorus': 248,
      'Calcium': 22,
      'Iron': 2.6,
      'Zinc': 5.2,
      'Copper': 0.10,
      'Selenium': 31.5,
      'Iodine': 14,
    },
  },
  {
    id: 'salmon-atlantic-cooked',
    name: 'Atlantic salmon (baked/grilled)',
    category: 'Proteins',
    kcal: 206,
    protein: 22.1,
    carbs: 0.0,
    fat: 12.4,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 61,
    portionTip: '1 fillet ≈ 150g',
    micros: {
      'Vitamin A': 15,
      'Vitamin D': 11.0,
      'Vitamin E': 2.8,
      'Vitamin B1': 0.23,
      'Vitamin B2': 0.15,
      'Vitamin B3': 8.5,
      'Vitamin B5': 1.6,
      'Vitamin B6': 0.82,
      'Vitamin B7': 5.0,
      'Folate': 29,
      'Vitamin B12': 2.8,
      'Choline': 90.0,
      'Magnesium': 30,
      'Potassium': 384,
      'Phosphorus': 252,
      'Calcium': 12,
      'Iron': 0.8,
      'Zinc': 0.6,
      'Copper': 0.06,
      'Selenium': 36.5,
      'Iodine': 35,
    },
  },
  {
    id: 'tuna-canned-water',
    name: 'Tuna (canned in water, drained)',
    category: 'Proteins',
    kcal: 116,
    protein: 25.5,
    carbs: 0.0,
    fat: 0.8,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 247,
    portionTip: '1 standard can ≈ 130g drained',
    micros: {
      'Vitamin D': 2.0,
      'Vitamin B1': 0.03,
      'Vitamin B2': 0.07,
      'Vitamin B3': 13.3,
      'Vitamin B5': 0.3,
      'Vitamin B6': 0.43,
      'Vitamin B12': 2.5,
      'Choline': 29.0,
      'Magnesium': 31,
      'Potassium': 237,
      'Phosphorus': 200,
      'Calcium': 11,
      'Iron': 1.5,
      'Zinc': 0.8,
      'Selenium': 68.1,
      'Iodine': 42,
    },
  },
  {
    id: 'cod-cooked',
    name: 'Pacific cod (baked/steamed)',
    category: 'Proteins',
    kcal: 105,
    protein: 22.8,
    carbs: 0.0,
    fat: 0.9,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 78,
    portionTip: '1 fillet ≈ 140g',
    micros: {
      'Vitamin D': 1.0,
      'Vitamin B1': 0.05,
      'Vitamin B2': 0.06,
      'Vitamin B3': 2.5,
      'Vitamin B5': 0.2,
      'Vitamin B6': 0.28,
      'Vitamin B12': 0.9,
      'Choline': 65.0,
      'Magnesium': 32,
      'Potassium': 413,
      'Phosphorus': 203,
      'Calcium': 16,
      'Iron': 0.4,
      'Zinc': 0.5,
      'Selenium': 33.1,
      'Iodine': 110,
    },
  },
  {
    id: 'shrimp-cooked',
    name: 'Shrimp (steamed/boiled)',
    category: 'Proteins',
    kcal: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 111,
    portionTip: '6-8 large shrimp ≈ 100g',
    micros: {
      'Vitamin A': 54,
      'Vitamin E': 2.2,
      'Vitamin B1': 0.03,
      'Vitamin B2': 0.03,
      'Vitamin B3': 2.6,
      'Vitamin B6': 0.1,
      'Vitamin B12': 1.1,
      'Choline': 135.0,
      'Magnesium': 39,
      'Potassium': 259,
      'Phosphorus': 237,
      'Calcium': 70,
      'Iron': 0.5,
      'Zinc': 1.6,
      'Copper': 0.3,
      'Selenium': 38.0,
      'Iodine': 40,
    },
  },
  {
    id: 'egg-whole-large',
    name: 'Egg (whole, hard-boiled/poached)',
    category: 'Proteins',
    kcal: 143,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0.0,
    sugar: 0.4,
    sodium: 142,
    portionTip: '1 large egg ≈ 50g',
    micros: {
      'Vitamin A': 160,
      'Vitamin D': 2.0,
      'Vitamin E': 1.0,
      'Vitamin B1': 0.04,
      'Vitamin B2': 0.46,
      'Vitamin B3': 0.1,
      'Vitamin B5': 1.4,
      'Vitamin B6': 0.17,
      'Vitamin B7': 20.0,
      'Folate': 47,
      'Vitamin B12': 0.9,
      'Choline': 294.0,
      'Magnesium': 12,
      'Potassium': 138,
      'Phosphorus': 198,
      'Calcium': 56,
      'Iron': 1.8,
      'Zinc': 1.3,
      'Copper': 0.07,
      'Selenium': 30.7,
      'Iodine': 49,
    },
  },
  {
    id: 'egg-whites-cooked',
    name: 'Egg whites (liquid or cooked)',
    category: 'Proteins',
    kcal: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    sugar: 0.7,
    sodium: 166,
    portionTip: 'Whites of 2 large eggs ≈ 66g',
    micros: {
      'Vitamin B2': 0.44,
      'Vitamin B3': 0.1,
      'Vitamin B5': 0.2,
      'Vitamin B7': 7.0,
      'Folate': 4,
      'Vitamin B12': 0.1,
      'Choline': 1.1,
      'Magnesium': 11,
      'Potassium': 163,
      'Phosphorus': 15,
      'Calcium': 7,
      'Iron': 0.1,
      'Zinc': 0.1,
      'Copper': 0.02,
      'Selenium': 20.0,
      'Iodine': 4,
    },
  },
  {
    id: 'whey-protein-isolate',
    name: 'Whey protein powder (80% isolate/blend)',
    category: 'Proteins',
    kcal: 380,
    protein: 80.0,
    carbs: 6.0,
    fat: 3.5,
    fiber: 1.0,
    sugar: 3.0,
    sodium: 180,
    portionTip: '1 standard scoop ≈ 30g (24g protein)',
    micros: {
      'Vitamin B2': 1.2,
      'Vitamin B12': 0.8,
      'Calcium': 450,
      'Phosphorus': 350,
      'Magnesium': 60,
      'Potassium': 400,
      'Iron': 0.5,
      'Zinc': 0.8,
      'Selenium': 25.0,
    },
  },

  // ==========================================
  // --- CARBOHYDRATES & GRAINS ---
  // ==========================================
  {
    id: 'oats-rolled-dry',
    name: 'Rolled oats (dry, whole grain)',
    category: 'Carbohydrates',
    kcal: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0.9,
    sodium: 2,
    portionTip: '1/2 cup dry ≈ 45g',
    micros: {
      'Vitamin B1': 0.70,
      'Vitamin B2': 0.14,
      'Vitamin B3': 1.0,
      'Vitamin B5': 1.3,
      'Vitamin B6': 0.12,
      'Vitamin B7': 14.0,
      'Folate': 32,
      'Choline': 32.0,
      'Magnesium': 138,
      'Potassium': 362,
      'Phosphorus': 410,
      'Calcium': 52,
      'Iron': 4.3,
      'Zinc': 3.6,
      'Copper': 0.60,
      'Manganese': 3.60,
      'Selenium': 28.9,
    },
  },
  {
    id: 'white-rice-cooked',
    name: 'White jasmine / basmati rice (cooked)',
    category: 'Carbohydrates',
    kcal: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0.1,
    sodium: 1,
    portionTip: '1 cup cooked ≈ 158g',
    micros: {
      'Vitamin B1': 0.16,
      'Vitamin B3': 1.5,
      'Folate': 58,
      'Potassium': 35,
      'Phosphorus': 43,
      'Magnesium': 13,
      'Calcium': 10,
      'Iron': 1.2,
      'Zinc': 0.5,
      'Manganese': 0.40,
      'Selenium': 7.5,
    },
  },
  {
    id: 'brown-rice-cooked',
    name: 'Brown rice (cooked, long-grain)',
    category: 'Carbohydrates',
    kcal: 112,
    protein: 2.3,
    carbs: 23.5,
    fat: 0.8,
    fiber: 1.8,
    sugar: 0.4,
    sodium: 1,
    portionTip: '1 cup cooked ≈ 195g',
    micros: {
      'Vitamin B1': 0.18,
      'Vitamin B2': 0.07,
      'Vitamin B3': 2.6,
      'Vitamin B5': 0.70,
      'Vitamin B6': 0.15,
      'Folate': 9,
      'Choline': 9.0,
      'Magnesium': 39,
      'Potassium': 79,
      'Phosphorus': 103,
      'Calcium': 10,
      'Iron': 0.5,
      'Zinc': 1.0,
      'Copper': 0.10,
      'Manganese': 1.10,
      'Selenium': 9.8,
    },
  },
  {
    id: 'sweet-potato-baked',
    name: 'Sweet potato (baked with skin)',
    category: 'Carbohydrates',
    kcal: 90,
    protein: 2.0,
    carbs: 20.7,
    fat: 0.2,
    fiber: 3.3,
    sugar: 6.5,
    sodium: 36,
    portionTip: '1 medium sweet potato ≈ 150g',
    micros: {
      'Vitamin A': 961,
      'Vitamin C': 19.6,
      'Vitamin E': 0.7,
      'Vitamin B1': 0.11,
      'Vitamin B2': 0.11,
      'Vitamin B3': 1.5,
      'Vitamin B5': 0.88,
      'Vitamin B6': 0.29,
      'Folate': 6,
      'Choline': 13.0,
      'Potassium': 475,
      'Phosphorus': 54,
      'Magnesium': 27,
      'Calcium': 38,
      'Iron': 0.7,
      'Zinc': 0.3,
      'Copper': 0.16,
      'Manganese': 0.50,
    },
  },
  {
    id: 'potato-russet-boiled',
    name: 'Russet potato (boiled/baked flesh & skin)',
    category: 'Carbohydrates',
    kcal: 87,
    protein: 1.9,
    carbs: 20.1,
    fat: 0.1,
    fiber: 1.8,
    sugar: 0.9,
    sodium: 4,
    portionTip: '1 medium potato ≈ 170g',
    micros: {
      'Vitamin C': 12.8,
      'Vitamin B1': 0.11,
      'Vitamin B3': 1.4,
      'Vitamin B5': 0.50,
      'Vitamin B6': 0.30,
      'Folate': 18,
      'Choline': 14.0,
      'Potassium': 417,
      'Phosphorus': 52,
      'Magnesium': 23,
      'Calcium': 12,
      'Iron': 0.8,
      'Zinc': 0.3,
      'Copper': 0.11,
      'Manganese': 0.15,
    },
  },
  {
    id: 'whole-wheat-pasta-cooked',
    name: 'Whole wheat pasta (cooked)',
    category: 'Carbohydrates',
    kcal: 148,
    protein: 6.0,
    carbs: 30.5,
    fat: 0.8,
    fiber: 4.5,
    sugar: 0.8,
    sodium: 3,
    portionTip: '1 cup cooked ≈ 140g',
    micros: {
      'Vitamin B1': 0.14,
      'Vitamin B2': 0.08,
      'Vitamin B3': 1.8,
      'Vitamin B6': 0.14,
      'Folate': 21,
      'Magnesium': 42,
      'Potassium': 95,
      'Phosphorus': 125,
      'Calcium': 19,
      'Iron': 1.5,
      'Zinc': 1.3,
      'Copper': 0.20,
      'Manganese': 1.00,
      'Selenium': 26.4,
    },
  },
  {
    id: 'white-pasta-cooked',
    name: 'Pasta / Spaghetti (enriched, cooked)',
    category: 'Carbohydrates',
    kcal: 158,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 1,
    portionTip: '1 cup cooked ≈ 140g',
    micros: {
      'Vitamin B1': 0.26,
      'Vitamin B2': 0.14,
      'Vitamin B3': 2.0,
      'Folate': 102,
      'Magnesium': 18,
      'Potassium': 44,
      'Phosphorus': 58,
      'Calcium': 7,
      'Iron': 1.8,
      'Zinc': 0.5,
      'Selenium': 26.4,
    },
  },
  {
    id: 'quinoa-cooked',
    name: 'Quinoa (cooked)',
    category: 'Carbohydrates',
    kcal: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    sugar: 0.9,
    sodium: 7,
    portionTip: '1 cup cooked ≈ 185g',
    micros: {
      'Vitamin E': 0.6,
      'Vitamin B1': 0.11,
      'Vitamin B2': 0.11,
      'Vitamin B6': 0.12,
      'Folate': 42,
      'Choline': 23.0,
      'Magnesium': 64,
      'Potassium': 172,
      'Phosphorus': 152,
      'Calcium': 17,
      'Iron': 1.5,
      'Zinc': 1.1,
      'Copper': 0.19,
      'Manganese': 0.63,
      'Selenium': 2.8,
    },
  },
  {
    id: 'bread-whole-wheat',
    name: 'Whole wheat bread (standard commercial)',
    category: 'Carbohydrates',
    kcal: 247,
    protein: 13.0,
    carbs: 41.3,
    fat: 3.4,
    fiber: 6.0,
    sugar: 5.6,
    sodium: 455,
    portionTip: '1 slice ≈ 40g',
    micros: {
      'Vitamin B1': 0.39,
      'Vitamin B2': 0.16,
      'Vitamin B3': 4.3,
      'Vitamin B6': 0.21,
      'Folate': 44,
      'Magnesium': 75,
      'Potassium': 248,
      'Phosphorus': 212,
      'Calcium': 107,
      'Iron': 2.5,
      'Zinc': 1.8,
      'Manganese': 1.80,
      'Selenium': 28.8,
    },
  },

  // ==========================================
  // --- FRUITS & VEGETABLES ---
  // ==========================================
  {
    id: 'broccoli-steamed',
    name: 'Broccoli (steamed/boiled florets)',
    category: 'Fruits & Vegetables',
    kcal: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    fiber: 3.3,
    sugar: 1.4,
    sodium: 41,
    portionTip: '1 cup florets ≈ 90g',
    micros: {
      'Vitamin A': 77,
      'Vitamin C': 64.9,
      'Vitamin E': 1.5,
      'Vitamin K': 141,
      'Vitamin B1': 0.06,
      'Vitamin B2': 0.12,
      'Vitamin B3': 0.6,
      'Vitamin B5': 0.60,
      'Vitamin B6': 0.20,
      'Folate': 65,
      'Choline': 40.0,
      'Potassium': 293,
      'Phosphorus': 67,
      'Calcium': 40,
      'Magnesium': 21,
      'Iron': 0.7,
      'Zinc': 0.4,
      'Manganese': 0.20,
    },
  },
  {
    id: 'spinach-raw',
    name: 'Baby spinach (raw fresh)',
    category: 'Fruits & Vegetables',
    kcal: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    portionTip: '2 cups raw leaves ≈ 60g',
    micros: {
      'Vitamin A': 469,
      'Vitamin C': 28.1,
      'Vitamin E': 2.0,
      'Vitamin K': 483,
      'Vitamin B1': 0.08,
      'Vitamin B2': 0.19,
      'Vitamin B6': 0.20,
      'Folate': 194,
      'Choline': 19.0,
      'Potassium': 558,
      'Phosphorus': 49,
      'Magnesium': 79,
      'Calcium': 99,
      'Iron': 2.7,
      'Zinc': 0.5,
      'Copper': 0.13,
      'Manganese': 0.90,
    },
  },
  {
    id: 'banana-raw',
    name: 'Banana (fresh, ripe)',
    category: 'Fruits & Vegetables',
    kcal: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12.2,
    sodium: 1,
    portionTip: '1 medium banana ≈ 118g',
    micros: {
      'Vitamin A': 3,
      'Vitamin C': 8.7,
      'Vitamin B1': 0.03,
      'Vitamin B2': 0.07,
      'Vitamin B3': 0.7,
      'Vitamin B5': 0.33,
      'Vitamin B6': 0.37,
      'Folate': 20,
      'Choline': 9.8,
      'Potassium': 358,
      'Phosphorus': 22,
      'Magnesium': 27,
      'Calcium': 5,
      'Iron': 0.3,
      'Zinc': 0.15,
      'Manganese': 0.27,
    },
  },
  {
    id: 'apple-medium-raw',
    name: 'Apple (fresh, with skin)',
    category: 'Fruits & Vegetables',
    kcal: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10.4,
    sodium: 1,
    portionTip: '1 medium apple ≈ 180g',
    micros: {
      'Vitamin A': 3,
      'Vitamin C': 4.6,
      'Vitamin E': 0.18,
      'Vitamin K': 2.2,
      'Folate': 3,
      'Potassium': 107,
      'Phosphorus': 11,
      'Calcium': 6,
      'Magnesium': 5,
      'Iron': 0.12,
    },
  },
  {
    id: 'blueberries-raw',
    name: 'Blueberries (fresh, raw)',
    category: 'Fruits & Vegetables',
    kcal: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    sugar: 10.0,
    sodium: 1,
    portionTip: '1 cup fresh ≈ 148g',
    micros: {
      'Vitamin A': 3,
      'Vitamin C': 9.7,
      'Vitamin E': 0.57,
      'Vitamin K': 19.3,
      'Folate': 6,
      'Potassium': 77,
      'Phosphorus': 12,
      'Magnesium': 6,
      'Calcium': 6,
      'Iron': 0.28,
      'Manganese': 0.34,
    },
  },
  {
    id: 'carrots-raw',
    name: 'Carrots (fresh, raw)',
    category: 'Fruits & Vegetables',
    kcal: 41,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    sugar: 4.7,
    sodium: 69,
    portionTip: '1 medium carrot ≈ 61g',
    micros: {
      'Vitamin A': 835,
      'Vitamin C': 5.9,
      'Vitamin K': 13.2,
      'Vitamin B6': 0.14,
      'Folate': 19,
      'Potassium': 320,
      'Phosphorus': 35,
      'Calcium': 33,
      'Magnesium': 12,
      'Iron': 0.3,
    },
  },
  {
    id: 'avocado-raw',
    name: 'Avocado (fresh, Haas)',
    category: 'Fruits & Vegetables',
    kcal: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7,
    portionTip: '1/2 medium avocado ≈ 100g',
    micros: {
      'Vitamin A': 7,
      'Vitamin C': 10.0,
      'Vitamin E': 2.07,
      'Vitamin K': 21.0,
      'Vitamin B1': 0.07,
      'Vitamin B2': 0.13,
      'Vitamin B3': 1.7,
      'Vitamin B5': 1.39,
      'Vitamin B6': 0.26,
      'Folate': 81,
      'Choline': 14.2,
      'Potassium': 485,
      'Phosphorus': 52,
      'Magnesium': 29,
      'Calcium': 12,
      'Iron': 0.55,
      'Zinc': 0.64,
      'Copper': 0.19,
    },
  },

  // ==========================================
  // --- DAIRY & ALTERNATIVES ---
  // ==========================================
  {
    id: 'greek-yogurt-nonfat',
    name: 'Greek yogurt (plain, non-fat 0%)',
    category: 'Dairy & Alternatives',
    kcal: 59,
    protein: 10.2,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0.0,
    sugar: 3.2,
    sodium: 36,
    portionTip: '1 single container ≈ 170g (17g protein)',
    micros: {
      'Vitamin A': 2,
      'Vitamin B2': 0.28,
      'Vitamin B5': 0.39,
      'Vitamin B12': 0.75,
      'Folate': 7,
      'Choline': 15.0,
      'Potassium': 141,
      'Phosphorus': 135,
      'Calcium': 110,
      'Magnesium': 11,
      'Zinc': 0.52,
      'Iodine': 35,
      'Selenium': 9.7,
    },
  },
  {
    id: 'cottage-cheese-lowfat',
    name: 'Cottage cheese (low-fat 1-2% milkfat)',
    category: 'Dairy & Alternatives',
    kcal: 72,
    protein: 12.4,
    carbs: 2.7,
    fat: 1.0,
    fiber: 0.0,
    sugar: 2.7,
    sodium: 406,
    portionTip: '1/2 cup ≈ 113g',
    micros: {
      'Vitamin A': 11,
      'Vitamin B2': 0.16,
      'Vitamin B5': 0.22,
      'Vitamin B12': 0.63,
      'Folate': 12,
      'Choline': 18.0,
      'Potassium': 125,
      'Phosphorus': 134,
      'Calcium': 61,
      'Magnesium': 8,
      'Zinc': 0.40,
      'Selenium': 9.0,
      'Iodine': 26,
    },
  },
  {
    id: 'milk-whole',
    name: 'Whole milk (pasteurized, 3.25% fat)',
    category: 'Dairy & Alternatives',
    kcal: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0.0,
    sugar: 5.1,
    sodium: 43,
    portionTip: '1 glass (8 fl oz) ≈ 244g',
    micros: {
      'Vitamin A': 46,
      'Vitamin D': 1.3,
      'Vitamin B1': 0.05,
      'Vitamin B2': 0.18,
      'Vitamin B5': 0.36,
      'Vitamin B12': 0.45,
      'Folate': 5,
      'Choline': 14.0,
      'Potassium': 132,
      'Phosphorus': 84,
      'Calcium': 113,
      'Magnesium': 10,
      'Zinc': 0.40,
      'Iodine': 42,
      'Selenium': 3.7,
    },
  },
  {
    id: 'almond-milk-unsweetened',
    name: 'Almond milk (unsweetened, commercial)',
    category: 'Dairy & Alternatives',
    kcal: 15,
    protein: 0.6,
    carbs: 0.3,
    fat: 1.2,
    fiber: 0.2,
    sugar: 0.0,
    sodium: 71,
    portionTip: '1 cup ≈ 240g',
    micros: {
      'Vitamin D': 1.0,
      'Vitamin E': 3.3,
      'Vitamin B12': 0.4,
      'Calcium': 184,
      'Potassium': 67,
      'Magnesium': 7,
    },
  },

  // ==========================================
  // --- FATS & NUTS ---
  // ==========================================
  {
    id: 'olive-oil-extra-virgin',
    name: 'Extra virgin olive oil',
    category: 'Fats & Nuts',
    kcal: 884,
    protein: 0.0,
    carbs: 0.0,
    fat: 100.0,
    fiber: 0.0,
    sugar: 0.0,
    sodium: 2,
    portionTip: '1 tablespoon ≈ 14g (120 kcal)',
    micros: {
      'Vitamin E': 14.3,
      'Vitamin K': 60.2,
      'Iron': 0.56,
      'Calcium': 1,
      'Potassium': 1,
    },
  },
  {
    id: 'almonds-raw',
    name: 'Almonds (raw, whole)',
    category: 'Fats & Nuts',
    kcal: 579,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    portionTip: '1 handful (approx 23 nuts) ≈ 28g',
    micros: {
      'Vitamin E': 25.6,
      'Vitamin B1': 0.21,
      'Vitamin B2': 1.14,
      'Vitamin B3': 3.6,
      'Vitamin B6': 0.14,
      'Vitamin B7': 17.0,
      'Folate': 44,
      'Choline': 52.0,
      'Potassium': 733,
      'Phosphorus': 481,
      'Magnesium': 270,
      'Calcium': 269,
      'Iron': 3.7,
      'Zinc': 3.1,
      'Copper': 1.03,
      'Manganese': 2.29,
      'Selenium': 4.1,
    },
  },
  {
    id: 'peanut-butter-natural',
    name: 'Natural peanut butter (peanuts only)',
    category: 'Fats & Nuts',
    kcal: 588,
    protein: 25.1,
    carbs: 20.0,
    fat: 50.4,
    fiber: 6.0,
    sugar: 9.2,
    sodium: 17,
    portionTip: '2 tablespoons ≈ 32g',
    micros: {
      'Vitamin E': 9.0,
      'Vitamin B1': 0.14,
      'Vitamin B3': 13.4,
      'Vitamin B5': 1.1,
      'Vitamin B6': 0.44,
      'Vitamin B7': 18.0,
      'Folate': 74,
      'Choline': 63.0,
      'Potassium': 649,
      'Phosphorus': 358,
      'Magnesium': 154,
      'Calcium': 43,
      'Iron': 1.9,
      'Zinc': 2.9,
      'Copper': 0.50,
      'Manganese': 1.50,
      'Selenium': 5.6,
    },
  },

  // ==========================================
  // --- LEGUMES & PLANT ---
  // ==========================================
  {
    id: 'black-beans-cooked',
    name: 'Black beans (boiled without salt)',
    category: 'Legumes & Plant',
    kcal: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    sugar: 0.3,
    sodium: 1,
    portionTip: '1 cup cooked ≈ 172g',
    micros: {
      'Vitamin B1': 0.24,
      'Vitamin B3': 0.5,
      'Vitamin B5': 0.24,
      'Vitamin B6': 0.07,
      'Folate': 149,
      'Choline': 31.0,
      'Potassium': 355,
      'Phosphorus': 140,
      'Magnesium': 60,
      'Calcium': 27,
      'Iron': 2.1,
      'Zinc': 1.1,
      'Copper': 0.21,
      'Manganese': 0.44,
      'Selenium': 1.2,
    },
  },
  {
    id: 'lentils-red-cooked',
    name: 'Red lentils (boiled without salt)',
    category: 'Legumes & Plant',
    kcal: 116,
    protein: 9.0,
    carbs: 20.1,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 2,
    portionTip: '1 cup cooked ≈ 198g',
    micros: {
      'Vitamin B1': 0.17,
      'Vitamin B2': 0.07,
      'Vitamin B3': 1.1,
      'Vitamin B6': 0.18,
      'Folate': 181,
      'Choline': 32.0,
      'Potassium': 369,
      'Phosphorus': 180,
      'Magnesium': 36,
      'Calcium': 19,
      'Iron': 3.3,
      'Zinc': 1.3,
      'Copper': 0.25,
      'Manganese': 0.49,
      'Selenium': 2.8,
    },
  },
  {
    id: 'tofu-firm',
    name: 'Firm tofu (prepared with calcium sulfate)',
    category: 'Legumes & Plant',
    kcal: 144,
    protein: 17.3,
    carbs: 2.8,
    fat: 8.7,
    fiber: 2.3,
    sugar: 0.6,
    sodium: 14,
    portionTip: '1/4 block ≈ 85g',
    micros: {
      'Vitamin B1': 0.16,
      'Vitamin B2': 0.10,
      'Folate': 29,
      'Choline': 29.0,
      'Potassium': 237,
      'Phosphorus': 190,
      'Calcium': 683,
      'Magnesium': 58,
      'Iron': 2.7,
      'Zinc': 1.6,
      'Copper': 0.38,
      'Manganese': 1.18,
      'Selenium': 17.4,
    },
  },
  {
    id: 'honey-pure',
    name: 'Pure raw honey',
    category: 'Legumes & Plant',
    kcal: 304,
    protein: 0.3,
    carbs: 82.4,
    fat: 0.0,
    fiber: 0.2,
    sugar: 82.1,
    sodium: 4,
    portionTip: '1 tablespoon ≈ 21g',
    micros: {
      'Potassium': 52,
      'Phosphorus': 4,
      'Calcium': 6,
      'Magnesium': 2,
      'Iron': 0.4,
      'Zinc': 0.2,
    },
  },
];

/**
 * Calculates scaled macronutrient amounts for a given food and gram weight.
 * e.g. 200g scales base values (per 100g) by 2x.
 */
export function calculateServingNutrients(food: VerifiedFood, grams: number) {
  const multiplier = Math.max(0, grams) / 100;
  return {
    kcal: Math.round(food.kcal * multiplier),
    protein: Math.round(food.protein * multiplier * 10) / 10,
    carbs: Math.round(food.carbs * multiplier * 10) / 10,
    fat: Math.round(food.fat * multiplier * 10) / 10,
    fiber: Math.round(food.fiber * multiplier * 10) / 10,
    sugar: Math.round(food.sugar * multiplier * 10) / 10,
    sodium: Math.round(food.sodium * multiplier),
  };
}

/**
 * Calculates scaled micronutrients (vitamins & minerals) for a given food and gram weight.
 * Values are rounded accurately based on typical magnitude.
 */
export function calculateServingMicros(food: VerifiedFood, grams: number): Record<string, number> {
  const multiplier = Math.max(0, grams) / 100;
  const result: Record<string, number> = {};
  if (food.micros) {
    for (const [key, val] of Object.entries(food.micros)) {
      if (typeof val === 'number' && val > 0) {
        // Trace vitamins with small values (< 1) keep 2 decimals, otherwise 1 decimal
        const scaled = val * multiplier;
        if (scaled < 1) {
          result[key] = Math.round(scaled * 100) / 100;
        } else {
          result[key] = Math.round(scaled * 10) / 10;
        }
      }
    }
  }
  return result;
}
